# config/default.yaml
# This file collects all default hyper-parameters.  It can be overridden
# from the command-line or by passing a different yaml file.

batch_size: 8
image_size: 64
num_steps: 500
lr: 1e-3
use_rechunet: 0
chunk_hw: 2
chunk_tb: 2
